### ISSUE TITLE
Can you also point a mapping list of all the environment variable to the subsequent SPO list.

### ISSUE THREAD

**Issue by shalabhgupta1985** [ivan-apps/PowerApps#2]
The SPO List Template count does not match the number of environment variable and I am confused which EV maps to which list in SPO.

Also because the solution is managed, Its not letting me update the environment variables post import.

**Comment by ivan-apps** [comment]
Environment variables should be possible to update, as long as you've added them to a local unmanaged solution. Can you share which mappings are missing or which you have questions on?

**Comment by shalabhgupta1985** [comment]
I was able to figure this out. Thanks a lot.
