### ISSUE TITLE
PIV Signatures?

### ISSUE THREAD

**Issue by shalabhgupta1985** [ivan-apps/PowerApps#3]
I was wondering if you are performing PIV signatures in this app? If yes, can you please assist me in just that part

**Comment by ivan-apps** [comment]
No, there is not PIV certificate connection made. That is what a 'digital signature' is and has validation against a CA. What I implement is an 'e-signature' which does not have that same requirement but is still a legally binding signature. Non-repudiation is handled by the CAC authentication into the tenants within DoD tenants. As long as you audit everything appropriately you should be good to go.

**Comment by shalabhgupta1985** [comment]
Okay, I am trying to implement a PIV Signature to my power app and was wondering if you have any suggestions or resources you can point me to, to move ahead. Thanks again for your help.
